const characters = [
	// The Elandys Family
	{
		faction: 'elandys-family',
		slug: 'mariel-elandys',
		name: 'Mariel Elandys – The Last True Seraph',
		desc: 'The current Queen of Eldynia and the final pure-blooded seraph, Mariel rules with calculated aggression and unshakable confidence. Though she lacks the overwhelming strength of her ancestors, her sharp wit and commanding presence deter challengers. Through sheer force of will, she maintains the illusion of invincibility, ensuring her kingdom’s survival in an era of decline.',
		image: '/characters/unknown-portrait.png',
		icon: '/character-border.png',
		VA: 'Vannes Theo Sudarsono',
	},
	{
		faction: 'elandys-family',
		slug: 'kazmiel-elandys',
		name: 'Kazmiel Elandys – The Pantocrator',
		image: '/characters/kazmiel.png',
		icon: '/characters/kazmielicon.png',
		desc: 'Mariel’s firstborn, a half-seraph, was born without wings, a mark of no divinity. Yet, when her father was slain, Kazmiel awakened her latent power, manifesting glowing wings and ascending as one of history’s most formidable warriors. Her plundering missions brought immeasurable wealth to Eldynia, but her love for a lowlander led to her abandoning war. Deemed a traitor to the crown, she was exiled, removed from history.',
		VA: 'Vannes Theo Sudarsono',
	},
	{
		faction: 'elandys-family',
		slug: 'vael-elandys',
		name: 'Vael Elandys – The Crown’s Final Hope',
		image: '/characters/unknown-portrait.png',
		icon: '/character-border.png',
		desc: 'The second child of Queen Mariel, Vael was born with wings, a symbol of his boundless potential. As a youth, he achieved the impossible by drawing the legendary Seraphic Blade Extharion from the stone at Castle Vrosk’s gardens, a feat none before him could accomplish. With his prodigious strength and divine destiny, he represents Eldynia’s brightest hope for restoration.',
		VA: 'Vannes Theo Sudarsono',
	},
	{
		faction: 'elandys-family',
		slug: 'flaire-eladryn',
		name: 'Flaire Eldryn – The Grand Mage',
		image: '/characters/flaire.png',
		icon: '/characters/flaireicon.png',
		desc: 'The enigmatic Grand Mage of Eldynia, Flaire serves as both advisor and caretaker to the royal family. Despite her claims of being human, her unnaturally long life, spanning even the Queen’s reign, hints at hidden origins. Knowledgeable, discreet, and impossibly ancient, she has guided three generations of Elandys rulers, her true motives as veiled as her past.',
		VA: 'Vannes Theo Sudarsono',
	},
	{
		faction: 'elandys-family',
		slug: 'deathless-king',
		name: '????? - The Deathless King',
		image: '/characters/deathlessking.png',
		icon: '/characters/deathlesskingicon.png',
		desc: 'A swordsman with extraordinary powers.',
		VA: 'Jordy Sword',
	},
	
	// The Brimvahl Guards
	{
		faction: 'brimvahl-guards',
		slug: 'elite-guard-tarva',
		name: 'Elite Guard Tarva',
		image: '/characters/femaleeliteguard.png',
		icon: '/characters/femaleeliteguardicon.png',
		desc: 'The Tarva units are typically female faunakins, specializing in locating treasures, swift plundering, and eliminating enemy cavalry units; their faunakin traits allow them to sense treasure locations, move with exceptional agility and flexibility, and communicate with the beasts ridden by cavalry, making them ideal for these tasks. Their armor is designed for speed, offering protection only to vital areas.',
		VA: 'Anna Faye',
	},
	{
		faction: 'brimvahl-guards',
		slug: 'elite-guard-tarvon',
		name: 'Elite Guard Tarvon',
		image: '/characters/maleeliteguard.png',
		icon: '/characters/maleeliteguardicon.png',
		desc: 'Composed primarily of male humans for their adaptability and inconspicuousness, Tarvon units specialize in covert infiltration, targeted assassinations, and the neutralization of enemy artillery. Their armor is fully enclosed, featuring a protective hood to minimize exposure to lethal injuries. Designed for stealth and precision, these operatives execute high-risk missions behind enemy lines with lethal efficiency.',
		VA: 'Leo Culligan',
	},	
	{
		faction: 'brimvahl-guards',
		slug: 'elite-guard-durnas',
		name: 'Elite Guard Durnas',
		image: '/characters/bruteguard.png',
		icon: '/characters/bruteguardicon.png',
		desc: 'Durnas units are predominantly composed of orcs and even giants, leveraging their immense strength and near-impenetrable defenses. While their size may hinder speed, they compensate with devastating offensive capabilities and unmatched resilience. Their primary role is to overwhelm and demoralize enemy forces, serving as the vanguard in large-scale assaults to crush opposition through sheer force.',
		VA: 'Vannes Theo Sudarsono',
	},
	{
		faction: 'brimvahl-guards',
		slug: 'regular-knight',
		name: 'Regular Knight',
		image: '/characters/regularknight.png',
		icon: '/characters/regularknighticon.png',
		desc: 'The Guards represent Eldynia’s most coveted profession, offering unmatched pay, residence in Castle Vrosk, and open recruitment to all, regardless of background and status. The sole requirement? Surviving the grueling Arena Challenge, where applicants must endure five minutes against an elite guard. Those who succeed join the ranks of Eldynia’s guards and on their path to become an elite guard after surviving a minimum of 5 pillage missions.',
		VA: 'Vannes Theo Sudarsono',
	},
	
	// Unknown Faction 1
	{
		faction: 'unknown1',
		slug: 'unknown',
		name: 'Unknown 1',
		image: '/characters/unknown-portrait.png',
		icon: '/character-border.png',
		desc: 'Unknown character, still searching for its information...',
		VA: 'Vannes Theo Sudarsono',
	},
	{
		faction: 'unknown1',
		slug: 'unknown',
		name: 'Unknown 2',
		image: '/characters/unknown-portrait.png',
		icon: '/character-border.png',
		desc: 'Also unknown character, still searching for its information...',
		VA: 'Vannes Theo Sudarsono',
	},
	{
		faction: 'unknown1',
		slug: 'unknown',
		name: 'Unknown 3',
		image: '/characters/unknown-portrait.png',
		icon: '/character-border.png',
		desc: 'Another unknown character again, still searching for its information...',
		VA: 'Vannes Theo Sudarsono',
	},
	{
		faction: 'unknown1',
		slug: 'unknown',
		name: 'Unknown 4',
		image: '/characters/unknown-portrait.png',
		icon: '/character-border.png',
		desc: 'Also unknown character, still searching for its information...',
		VA: 'Vannes Theo Sudarsono',
	},
	{
		faction: 'unknown1',
		slug: 'unknown',
		name: 'Unknown 5',
		image: '/characters/unknown-portrait.png',
		icon: '/character-border.png',
		desc: 'Another unknown character again, still searching for its information...',
		VA: 'Vannes Theo Sudarsono',
	},
	{
		faction: 'unknown1',
		slug: 'unknown',
		name: 'Unknown 6',
		image: '/characters/unknown-portrait.png',
		icon: '/character-border.png',
		desc: 'Another unknown character again, still searching for its information...',
		VA: 'Vannes Theo Sudarsono',
	},

	// Unknown Faction 2
	{
		faction: 'unknown2',
		slug: 'unknown',
		name: 'Unknown 1',
		image: '/characters/unknown-portrait.png',
		icon: '/character-border.png',
		desc: 'Unknown character, still searching for its information...',
		VA: 'Vannes Theo Sudarsono',
	},
	{
		faction: 'unknown2',
		slug: 'unknown',
		name: 'Unknown 2',
		image: '/characters/unknown-portrait.png',
		icon: '/character-border.png',
		desc: 'Also unknown character, still searching for its information...',
		VA: 'Vannes Theo Sudarsono',
	},
	{
		faction: 'unknown2',
		slug: 'unknown',
		name: 'Unknown 3',
		image: '/characters/unknown-portrait.png',
		icon: '/character-border.png',
		desc: 'Another unknown character again, still searching for its information...',
		VA: 'Vannes Theo Sudarsono',
	},

	// Unknown Faction 3
	{
		faction: 'unknown3',
		slug: 'unknown',
		name: 'Unknown 1',
		image: '/characters/unknown-portrait.png',
		icon: '/character-border.png',
		desc: 'Unknown character, still searching for its information...',
		VA: 'Vannes Theo Sudarsono',
	},
	{
		faction: 'unknown3',
		slug: 'unknown',
		name: 'Unknown 2',
		image: '/characters/unknown-portrait.png',
		icon: '/character-border.png',
		desc: 'Also unknown character, still searching for its information...',
		VA: 'Vannes Theo Sudarsono',
	},
	{
		faction: 'unknown3',
		slug: 'unknown',
		name: 'Unknown 3',
		image: '/characters/unknown-portrait.png',
		icon: '/character-border.png',
		desc: 'Another unknown character again, still searching for its information...',
		VA: 'Vannes Theo Sudarsono',
	},
	{
		faction: 'unknown3',
		slug: 'unknown',
		name: 'Unknown 4',
		image: '/characters/unknown-portrait.png',
		icon: '/character-border.png',
		desc: 'Also unknown character, still searching for its information...',
		VA: 'Vannes Theo Sudarsono',
	},
];

export default characters;